[package]
name = "x86emu"
version = "0.0.0"
authors = ["fotcorn <fotcorn@gmail.com>", "Matthias Fauconneau <matthias.fauconneau@gmail.com"]
edition = '2018'

[dependencies]
#object = ""
addr2line = ""
fnv = ""
bitflags = ""
goblin = ""
uefi = { path = "../uefi" }
